FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH="/app"

WORKDIR /app

COPY requiriments.txt .
RUN pip install --no-cache-dir -r requiriments.txt

COPY etl ./etl
COPY backend/app/core ./backend/app/core

CMD ["sleep", "infinity"]
